<?php
$pageTitle = 'MC Exodus Videos, Comedy and Event Media';
$pageDescription = 'Watch MC Exodus on YouTube, TikTok, Instagram and Facebook, and explore real photographs from weddings, appearances and comedy content.';
$pageKey = 'media';
$canonicalPath = 'media.php';
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><p class="eyebrow">Videos and media</p><h1>On stage, on screen and in the moment.</h1><p>Follow official MC Exodus channels for the latest performances, comedy clips, event highlights and announcements.</p></div></section>
<section class="band band-dark"><div class="container"><div class="social-panel reveal"><a href="<?= e($site['socials']['youtube']) ?>" target="_blank" rel="noopener"><img src="/assets/img/studio-appearance.jpg" alt="MC Exodus studio appearance" loading="lazy"><span><strong>YouTube</strong><br><small>Long-form videos and comedy</small></span></a><a href="<?= e($site['socials']['tiktok']) ?>" target="_blank" rel="noopener"><img src="/assets/img/character-outdoor.jpg" alt="MC Exodus comedy character outdoors" loading="lazy"><span><strong>TikTok</strong><br><small>Short comedy and live moments</small></span></a><a href="<?= e($site['socials']['instagram']) ?>" target="_blank" rel="noopener"><img src="/assets/img/portrait-outdoor.jpg" alt="MC Exodus portrait" loading="lazy"><span><strong>Instagram</strong><br><small>Highlights and behind the scenes</small></span></a><a href="<?= e($site['socials']['facebook']) ?>" target="_blank" rel="noopener"><img src="/assets/img/wedding-mc.jpg" alt="MC Exodus hosting a wedding" loading="lazy"><span><strong>Facebook</strong><br><small>Updates, video and community</small></span></a></div></div></section>
<section class="band"><div class="container"><div class="section-head reveal"><div><p class="eyebrow">Photo journal</p><h2>Selected moments from real work.</h2></div></div><div class="media-strip reveal"><div class="media-tile"><img src="/assets/img/wedding-mc.jpg" alt="MC Exodus performing at a wedding"><span>Hosting a wedding celebration</span></div><div class="media-tile"><img src="/assets/img/studio-appearance.jpg" alt="MC Exodus at a studio appearance"><span>Studio appearance</span></div><div class="media-tile"><img src="/assets/img/comedy-scene-two.jpg" alt="MC Exodus in a comedy scene"><span>Comedy content</span></div><div class="media-tile"><img src="/assets/img/market-content.jpg" alt="MC Exodus filming lifestyle content in a market"><span>Location content</span></div></div></div></section>
<section class="band band-soft"><div class="container split"><div class="split-image reveal"><img src="/assets/img/wedding-crowd-one.jpg" alt="Wedding guests enjoying a lively hosted moment" loading="lazy"></div><div class="reveal"><p class="eyebrow">Book the experience</p><h2>Like what you see? Bring that energy to your audience.</h2><p class="lead">Share the event date, location, audience and programme. The team will review the request and respond privately about availability.</p><div class="action-row"><a class="button" href="/book.php">Book MC Exodus</a></div></div></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
